### ISSUE TITLE
Suggestion: default inventory

### ISSUE THREAD

**Issue by ustm** [larsks/ansible-toolbox#11]
I have a suggestion.
How about using inventory from ansible.cfg by default instead of localhost?

Or the same way as ansible do it:
- ANSIBLE_CONFIG (an environment variable)
- ansible.cfg (in the current directory)
- .ansible.cfg (in the home directory)
- /etc/ansible/ansible.cfg

**Comment by larsks** [comment]
You can already do this.  The ansible-toolbox commands don't provide ansible with any inventory, so ansible just uses it's normal mechanism for locating an inventory.  You can use the `--hosts` (`-H`) option to specify a host other than localhost.

In other words, if you have in your `~/.ansible.cfg`:

    [default]
    inventory = ~/.ansible_hosts

And in `~/.ansible_hosts` you have:

    remote1 ansible_host=127.0.0.1

Then you can simply run:

    ansible-eval -H remote1 '{{ ansible_eth0 }}'
