### ISSUE TITLE
run with sudo

### ISSUE THREAD

**Issue by rabeloo** [larsks/ansible-toolbox#3]
Hi, 
I found this issue while run ansible-role with sudo command:

`Traceback (most recent call last):
  File "/usr/local/bin/ansible-role", line 9, in <module>
    load_entry_point('ansible-toolbox==0.2', 'console_scripts', 'ansible-role')()
  File "build/bdist.linux-x86_64/egg/ansible_toolbox/cmd/role.py", line 37, in main
  File "build/bdist.linux-x86_64/egg/ansible_toolbox/cmd/role.py", line 33, in main
  File "/usr/lib64/python2.7/subprocess.py", line 536, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`

To reproduce, just type:

`
$ sudo ansible-role role_name
`

Has some way to run it with sudo?

Thanks

**Comment by saitejamc** [comment]
@rabeloo Hey, I just installed ansible-toolbox and ran ansible-role command with sudo as well. It just works fine. I tried it on CentOS 7.

`[root@localhost roles]# ansible-role -i all test.result/
 [WARNING]: Host file not found: all

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [test.result/ : echo hello world] *****************************************
changed: [localhost]

TASK [test.result/ : search for saiteja in users] ******************************
changed: [localhost]

TASK [test.result/ : echo register stdin] **************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=3    unreachable=0    failed=0   

[root@localhost roles]# sudo ansible-role -i all test.result/
 [WARNING]: Host file not found: all

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [test.result/ : echo hello world] *****************************************
changed: [localhost]

TASK [test.result/ : search for saiteja in users] ******************************
changed: [localhost]

TASK [test.result/ : echo register stdin] **************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=3    unreachable=0    failed=0   


`
