### ISSUE TITLE
No installation instructions

### ISSUE THREAD

**Issue by flickerfly** [larsks/ansible-toolbox#6]
This looks interesting and I would like to try it out. Is this an ansible module? If so, how do I install it? A little section with some pointers in the readme about getting it running would be really helpful for those of us unfamiliar with what you wrote here. 

Thanks!

**Comment by Atem18** [comment]
@flickerfly Instructions are clear, you need to clone the repo : ```git clone https://github.com/larsks/ansible-toolbox.git```, then cd into ```cd ansible-toolbox``` and make a ```python setup.py install``` to install it.

Or you can install it from PyPi ```pip install ansible-toolbox``` because I needed to have a package for easy install.
src: https://pypi.python.org/pypi/ansible-toolbox/0.2


Have fun :)

**Comment by larsks** [comment]
Note that I do not maintain the pypi package currently, which means that it won't be updated regularly when I push new commits here. I recommend installing as described in the README.
